version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./site:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    build: .
    volumes:
      - ./site:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: phpclass
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbdev123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data: 